### PR TITLE
use simplejson if available

### PR DESCRIPTION
**Pull request by joshowen**
it gives a nice performance boost

### CODE REVIEW

**Comment by wbolster** [comment]
hi, thanks for your contribution.

i am not sure whether it's worth it to have this built-in. the performance boost is _not_ visible on py3.5 on linux for me:

```
>>> import json, simplejson

>>> s = '{"a":"foo","b":"bar","c":[1,2,3],"d":{}}'
>>> %timeit json.loads(s)
The slowest run took 12.19 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.86 µs per loop
>>> %timeit json.loads(s)
The slowest run took 6.19 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 2.88 µs per loop

>>> %timeit simplejson.loads(s)
The slowest run took 24.53 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 3.67 µs per loop
>>> %timeit simplejson.loads(s)
The slowest run took 7.33 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 3.73 µs per loop
```

also, `jsonlines.Writer` takes a `dumps=...` keyword arg, so it is already possible to plug in another json serialiser.

**Comment by wbolster** [comment]
using simplejson 3.10.0 btw

**Comment by joshowen** [comment]
It is a much bigger boost in 2.x

**Comment by wbolster** [comment]
ok. it's actually a slowdown on 3.x, and since 2.x is end of life, it makes sense leave the defaults as-is.

let me know if you have further questions or suggestions for this library!

**Pull request closed without merging**
