### PR TITLE
Fixing tests

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by wbolster** [comment]
not sure i agree on this one because of https://hynek.me/articles/testing-packaging/

**Comment by KOLANICH** [comment]
I don't understand how the link is relevant here.

**Comment by wbolster** [comment]
the main reason is that running against not installed code is potentially problematic. adding explicit path hacks for it feels wrong.

**Comment by KOLANICH** [comment]
>the main reason is that running against not installed code is potentially problematic.

It strongly depends on the package code. If it is not a namespace package or other hacks with folder structure, preventing `devel`, if `setup.py` doesn't trigger some code postprocessing like cext compilation or transpilation of somethingninto python, doesn't provide entry points and has correct imports, then it should work fine.

**Pull request closed without merging**
